### ISSUE TITLE
Who is maintaining this repo?

### ISSUE THREAD

**Issue by rexwangcc** [broadinstitute/dsde-deep-learning#11]
Hey, I'm just wondering who is maintaining this repo, is there a team who is working on Deep Learning? Or it is just a "Hobby Repo"? Because I'd like to contribute to building this repo if it is the latter case :)

**Comment by lucidtronix** [comment]
Hi @rexwangcc,  
I would be happy to review a PR if you submit one!
We started this repo to collect code examples as we worked our way through the [deep learning book](http://www.deeplearningbook.org).  We finished the book so there has been less activity lately. The repo may in the future become the home of the deep learning code we develop in DSP Methods group...

**Comment by rexwangcc** [comment]
Hi @lucidtronix , 
Thank you very much for your prompt reply and explanation! I heard that Palantir is developing some exciting DL methods on various data. I thought this repo was a part-time hobby repo for deep learning lovers within Broad, but since it's going to be an official home of the deep learning code of Methods, I'd like to just watch it instead of disturbing it before that, maybe it's better for me to find another place or create another repo for hobby use. Besides, it is my pleasure to submit PRs(pytorch/tf/dl4j) in the future. Thank you!
