### ISSUE TITLE
PyCharm support?

### ISSUE THREAD

**Issue by yfarjoun** [broadinstitute/dsde-deep-learning#6]
It would be great if we could figure out how to use pycharm in a well-integrated way...

my current problem is that when I turn on the python console within intelij I can't seem to figure out how to be inside the conda environment...

**Comment by lucidtronix** [comment]
@yfarjoun I got this to work by adding a new python interpreter to pycharm in Preferences > Project Interpreter.
I just had to point it at the anaconda envs python that I wanted to use.  Mine lived at 
```
/anaconda/envs/p3/bin/python
```
